export type Relay = {
	name: string;
	enabled: boolean;
	startup: boolean;
	pulseMs: number;
	disconnectOff: boolean;
	timeout: number;
};
export type Config = {
	schemaVersion: number;
	revision: number;
	relays: Relay[];
	rgb: boolean;
	buzzer: boolean;
	button: boolean;
	rs485: boolean;
	brightness: number;
	clicks: { action: number; target: number }[];
	mode: string;
	unit: number;
	baud: number;
	serialFormat: number;
	tcpPort: number;
	busMask: number;
	busIndicators: boolean;
	busWatchdog: boolean;
	tcpAllow: string;
};
export type Status = {
	revision: number;
	mode: string;
	protocolState: string;
	fault: number;
	error: string;
	sta: boolean;
	networkOnline: boolean;
	networkInterface: string;
	ip: string;
	ap: boolean;
	apClients: number;
	uptime: number;
	relays: { on: boolean; enabled: boolean; blocked: boolean; source: string }[];
	programming: boolean;
	knxConfigured: boolean;
	pressed: boolean;
	lastGesture: number;
	gestureCount: number;
	resetArmed: boolean;
	color: number[];
	toneHz: number;
	requests: number;
	frameErrors: number;
	rejected: number;
	configWindow: boolean;
	tcpClients: number;
	audit: string[];
	capabilities: { configure: boolean; command: boolean; admin: boolean; channels: number };
};
export type Knx = {
	revision: number;
	address: string;
	owner: string;
	configured: boolean;
	active: boolean;
	busy: boolean;
	developmentIdentity: boolean;
	objects: { number: number; groups: string[] }[];
	parameters: Omit<Relay, 'name'>[];
	takeover?: boolean;
};
