"""Generate ETS source and firmware constants from the same product contract.

Run from any directory. Packaging: OpenKNXproducer create knx/Edge_S3_Relay_6CH.xml
The development manufacturer identity must be replaced before commercial release.
"""

import json
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NS = "http://knx.org/xml/project/20"
ET.register_namespace("", NS)


def element(parent, tag, **attrs):
    return ET.SubElement(parent, f"{{{NS}}}{tag}", {k: str(v) for k, v in attrs.items()})


HEADER_TEMPLATE = """// Generated by scripts/generate_knx_product.py; do not edit.
#pragma once
namespace actuator::product {{
constexpr unsigned Manufacturer = {manufacturerId};
constexpr unsigned Application = {applicationNumber};
constexpr unsigned Version = {applicationVersion};
constexpr unsigned Channels = {channels};
constexpr unsigned ParameterBytes = {parameterBytes};
constexpr unsigned ObjectCount = Channels * 3;
constexpr unsigned channelOffset(unsigned channel) {{ return 4 + 8 * channel; }}
}}
"""


def add_parameters(static: ET.Element, model: dict) -> list[str]:
    element(
        element(static, "Code"),
        "RelativeSegment",
        Id="%AID%_RS-04-00000",
        Name="Parameters",
        Offset=0,
        Size=model["parameterBytes"],
        LoadStateMachine=4,
    )
    types = element(static, "ParameterTypes")
    for name, bits, low, high in [
        ("Boolean", 8, 0, 1),
        ("Format", 8, 1, 1),
        ("Flags", 8, 3, 3),
        ("Timeout", 16, 1, 3600),
        ("Pulse", 16, 10, 60000),
    ]:
        element(
            element(types, "ParameterType", Id=f"%AID%_PT-{name}", Name=name),
            "TypeNumber",
            SizeInBit=bits,
            Type="unsignedInt",
            minInclusive=low,
            maxInclusive=high,
        )
    parameters = element(static, "Parameters")
    refs = element(static, "ParameterRefs")
    dynamic_refs = []

    def parameter(name, kind, offset, default):
        n = len(dynamic_refs) + 1
        pid = f"%AID%_P-{n}"
        ref = f"{pid}_R-{n}"
        element(
            element(
                parameters,
                "Parameter",
                Id=pid,
                Name=name,
                Text=name,
                ParameterType=f"%AID%_PT-{kind}",
                Value=default,
            ),
            "Memory",
            CodeSegment="%AID%_RS-04-00000",
            Offset=offset,
            BitOffset=0,
        )
        element(refs, "ParameterRef", Id=ref, RefId=pid)
        dynamic_refs.append(ref)

    parameter("Parameter format", "Format", 0, 1)
    parameter("Global flags", "Flags", 1, 3)
    for c in range(model["channels"]):
        for name, kind, off, default in [
            ("Enabled", "Boolean", 0, 1),
            ("Startup ON", "Boolean", 1, 0),
            ("OFF on loss", "Boolean", 2, 0),
            ("Loss timeout seconds", "Timeout", 4, 30),
            ("Pulse milliseconds", "Pulse", 6, 1000),
        ]:
            parameter(f"Channel {c + 1} {name}", kind, 4 + 8 * c + off, default)
    return dynamic_refs


def add_objects(static: ET.Element, model: dict) -> None:
    objects = element(static, "ComObjectTable")
    object_refs = element(static, "ComObjectRefs")
    for number in range(1, model["channels"] * 3 + 1):
        status = number % 3 == 0
        kind = ["Status", "Switch", "Block"][number % 3]
        dpt = ["DPST-1-2", "DPST-1-1", "DPST-1-3"][number % 3]
        oid = f"%AID%_O-{number}"
        element(
            objects,
            "ComObject",
            Id=oid,
            Name=f"Channel {(number + 2) // 3} {kind}",
            Text=f"Channel {(number + 2) // 3} {kind}",
            Number=number,
            FunctionText=kind,
            ObjectSize="1 Bit",
            ReadFlag="Enabled" if status else "Disabled",
            WriteFlag="Disabled" if status else "Enabled",
            CommunicationFlag="Enabled",
            TransmitFlag="Enabled" if status else "Disabled",
            UpdateFlag="Disabled",
            ReadOnInitFlag="Disabled",
            DatapointType=dpt,
        )
        element(object_refs, "ComObjectRef", Id=f"{oid}_R-{number}", RefId=oid)


def build_product(model: dict) -> ET.Element:
    root = ET.Element(f"{{{NS}}}KNX", CreatedBy="Edge actuator generator", ToolVersion="1.0")
    manufacturer = element(element(root, "ManufacturerData"), "Manufacturer", RefId=f"M-{model['manufacturerId']:04X}")
    catalog = element(
        element(manufacturer, "Catalog"),
        "CatalogSection",
        Id=f"M-{model['manufacturerId']:04X}_CS-1",
        Name="Development",
        Number=1,
        DefaultLanguage="en-US",
    )
    element(
        catalog,
        "CatalogItem",
        Id="%CatalogItemId%",
        Name=model["name"],
        Number=1,
        ProductRefId="%ProductId%",
        Hardware2ProgramRefId="%Hardware2ProgramId%",
        DefaultLanguage="en-US",
    )
    app = element(
        element(manufacturer, "ApplicationPrograms"),
        "ApplicationProgram",
        Id="%AID%",
        ApplicationNumber=model["applicationNumber"],
        ApplicationVersion=model["applicationVersion"],
        ProgramType="ApplicationProgram",
        MaskVersion=model["maskVersion"],
        Name=model["name"],
        LoadProcedureStyle="MergedProcedure",
        PeiType=0,
        DefaultLanguage="en-US",
        DynamicTableManagement="false",
        Linkable="false",
        MinEtsVersion="5.0",
    )
    static = element(app, "Static")
    dynamic_refs = add_parameters(static, model)
    add_objects(static, model)
    element(static, "AddressTable", MaxEntries=model["maxGroupAddresses"])
    element(static, "AssociationTable", MaxEntries=model["maxAssociations"])
    loads = element(static, "LoadProcedures")
    element(
        element(loads, "LoadProcedure", MergeId=2),
        "LdCtrlRelSegment",
        AppliesTo="full",
        LsmIdx=4,
        Size=model["parameterBytes"],
        Mode=0,
        Fill=0,
    )
    element(
        element(loads, "LoadProcedure", MergeId=4),
        "LdCtrlWriteRelMem",
        ObjIdx=4,
        Offset=0,
        Size=model["parameterBytes"],
        Verify="true",
    )
    element(static, "Options")
    block = element(
        element(element(app, "Dynamic"), "ChannelIndependentBlock"),
        "ParameterBlock",
        Id="%AID%_PB-1",
        Name="Actuator",
        Text="Six-channel actuator",
    )
    for ref in dynamic_refs:
        element(block, "ParameterRefRef", RefId=ref)
    for n in range(1, model["channels"] * 3 + 1):
        element(block, "ComObjectRefRef", RefId=f"%AID%_O-{n}_R-{n}")
    hardware = element(
        element(manufacturer, "Hardware"),
        "Hardware",
        Id="%HardwareId%",
        Name=model["name"],
        SerialNumber=str(model["applicationNumber"]),
        VersionNumber=1,
        HasIndividualAddress="true",
        HasApplicationProgram="true",
        IsIPEnabled="true",
    )
    element(
        element(hardware, "Products"),
        "Product",
        Id="%ProductId%",
        Text=model["name"],
        OrderNumber="EDGE-S3-6CH-DEV",
        IsRailMounted="true",
        DefaultLanguage="en-US",
    )
    element(
        element(
            element(hardware, "Hardware2Programs"),
            "Hardware2Program",
            Id="%Hardware2ProgramId%",
            MediumTypes="MT-5",
        ),
        "ApplicationProgramRef",
        RefId="%AID%",
    )
    return root


def main() -> None:
    model = json.loads((ROOT / "knx/product-model.json").read_text(encoding="utf-8"))
    root = build_product(model)
    ET.indent(root, space="  ")
    ET.ElementTree(root).write(ROOT / "knx/Edge_S3_Relay_6CH.xml", encoding="utf-8", xml_declaration=True)
    header = ROOT / "src/generated/KnxProduct.h"
    header.parent.mkdir(exist_ok=True)
    header.write_text(HEADER_TEMPLATE.format(**model), encoding="utf-8")
    print("Generated six-channel ETS XML and firmware constants")


if __name__ == "__main__":
    main()
